### ISSUE TITLE
Great job simplifying the CSS code for shared properties.

### ISSUE THREAD

**Issue by josephtkim** [dcthomas10/prj-rev-bwfs-dasmoto#5]
You can simplify the CSS code further for several other shared properties, such as font-family and font-weight. You can do so by applying the properties to multiple selectors at once, rather than individually, like

```css
h1, h2, .price {
  font-weight: bold;
  font-family: Helvetica;
}
```
